title: Patryk Ptasiński's Dev & Life Blog
email: blog@ipepe.pl
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ipepe.pl" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ipepe

permalink: /:year/:month/:day/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .idea/
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

