title: Patryk Ptasiński's Dev & Life Blog
email: blog@ipepe.pl
author: Patryk Ptasiński
description: >- # this means to ignore newlines until "baseurl:"
  Patryk Ptasiński's Dev & Life Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ipepe.pl" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ipepe

permalink: /:year/:month/:day/:title/

show_excerpts: true
theme: minima
minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed

exclude:
  - .idea/
  - README.md
  - LICENSE
  - Gemfile
  - Rakefile
  - Gemfile.lock

